<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_consultant"
 *
 * Auto generated by Extension Builder 2015-09-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RKW Consultant',
	'description' => '',
	'category' => 'plugin',
    'author' => 'Maximilian Fäßler, Steffen Kroggel',
    'author_email' => 'maximilian@faesslerweb.de, developer@steffenkroggel.de',
    'author_company' => 'RKW Kompetenzzentrum',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.4',
	'constraints' => array(
		'depends' => array(
            'extbase' => '6.2.0-7.6.99',
            'fluid' => '6.2.0-7.6.99',
            'typo3' => '6.2.0-7.6.99',
            'rkw_basics' => '7.6.0-8.7.99',
			'rkw_mailer' => '7.6.0-8.7.99',
			'rkw_registration' => '7.6.10-8.7.99',
			'rkw_geolocation' => '7.6.10-8.7.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);