<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_consultant"
 *
 * Auto generated by Extension Builder 2015-09-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Consultant',
	'description' => '',
	'category' => 'plugin',
    'author' => 'Maximilian Fäßler, Steffen Kroggel',
    'author_email' => 'maximilian@faesslerweb.de, developer@steffenkroggel.de',
    'author_company' => 'RKW Kompetenzzentrum',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.7.3',
	'constraints' => [
		'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'rkw_basics' => '8.7.0-8.7.99',
			'rkw_mailer' => '8.7.0-8.7.99',
			'rkw_registration' => '8.7.0-8.7.99',
			'rkw_geolocation' => '8.7.0-8.7.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];